---
title: 'Connecting to the Yoda portal'
teaching: 10
exercises: 2
editor_options: 
  markdown: 
    wrap: 72
---

::: questions
-   How to connect to Yoda?
:::

::: objectives
-   Enter the Yoda web portal and access the tutorial workspace
:::

## Introduction

Let us enter the Yoda web portal now.

1.  Open a browser window. Navigate to the portal URL:

    -   For training hosted by SURF, the portal address is
        [https://surf-yoda.irods.surfsara.nl](https://surf-yoda.irods.surfsara.nl){target="_blank"}.
    -   For the addresses of institute-specific portals, see [this
        overview of
        URL's](https://servicedesk.surf.nl/wiki/spaces/WIKI/pages/19824782/Yoda+Hosting#YodaHosting-YodaHosting){target="_blank"}.
    -   Before you can login, course instructors should give you access
        to the portal.

2.  Log in with your credentials or
    [SRAM](https://sram.surf.nl/){target="_blank"} by clicking on
    `Sign in` and entering your email address. In your browser it should
    look something like this:

    ![Example of how the Yoda portal looks like once logged
    in](fig/yoda-portal.png){width="584"}

3.  Click on the Research tab Verify that you see two folders:
    `research-tutorial-unsup` and `research-tutorial-sup`.
    These two folders will represent two different groups that you will
    be working in

4.  Try to remember that we will start working in the unsupervised
    group, and only in the last exercise we will move to the other one.

::: instructor
Make sure you invite workshop participants beforehand to a research
group and provide a link to the correct portal address.
:::

::: keypoints
-   Use your institutional email address to enter the portal
-   You can only log in to Yoda when you are added to a specific Group
    in Yoda
:::
