---
title: 'Epilogue'
teaching: 5
exercises: 1
editor_options: 
  markdown: 
    wrap: 72
---

::: questions
-   What is next?
:::

Well done! You have now finished the exercises for today. You can be
proud of having completed some tough work today.

If you think anything is still unclear, do not hesitate to contact your
facilitators.

For next steps with regards to Yoda, you can visit our documentation
pages here: [Yoda
Hosting](https://servicedesk.surf.nl/wiki/spaces/WIKI/pages/19824782/Yoda+Hosting).

Thank you for your attention, and we hope to have been of help for you
today.


::: callout
## Complimentary information

-   A handy alternative interface to the YODA portal of a YODA instance
    is the [WebDAV](https://en.wikipedia.org/wiki/WebDAV){target="_blank"} interface:
    <https://surf-data.irods.surfsara.nl>{target="_blank"} (you can also use WebDAV to
    get access to Yoda through your local file manager, by mapping it as
    a [network
    disk](https://www.uu.nl/en/research/yoda/guide-to-yoda/accessing-yoda/connecting-to-the-yoda-network-disk){target="_blank"}).

-   A feature we have not touched in this hands-on session is
    Publishing. That is a next step in the flow after the Vault.

-   Yoda is open source, and you can view their code and advanced
    documentation in Utrecht University's GitHub:
    <https://github.com/UtrechtUniversity/yoda>{target="_blank"}
:::
